[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"
NETLIFY_USE_YARN = "false"

# Explicitly set environment variables for all contexts
[context.production]
  [context.production.environment]
  PUBLIC_GITHUB_USERNAME = "ecrotty"

[context.deploy-preview]
  [context.deploy-preview.environment]
  PUBLIC_GITHUB_USERNAME = "ecrotty"

[context.branch-deploy]
  [context.branch-deploy.environment]
  PUBLIC_GITHUB_USERNAME = "ecrotty"

[dev]
command = "npm run dev"
targetPort = 4321
