[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"
NETLIFY_USE_YARN = "false"

# Explicitly set environment variables for all contexts
[context.production]
  [context.production.environment]
  PUBLIC_GITHUB_USERNAME = "ecrotty"
  PUBLIC_SITE_TITLE = "Ed Crotty's Professional Portfolio - IT Leader"
  PUBLIC_SITE_DESCRIPTION = "Ed Crotty's Professional Portfolio - IT Leader"

[context.deploy-preview]
  [context.deploy-preview.environment]
  PUBLIC_GITHUB_USERNAME = "ecrotty"
  PUBLIC_SITE_TITLE = "Ed Crotty's Professional Portfolio - IT Leader"
  PUBLIC_SITE_DESCRIPTION = "Ed Crotty's Professional Portfolio - IT Leader"

[context.branch-deploy]
  [context.branch-deploy.environment]
  PUBLIC_GITHUB_USERNAME = "ecrotty"
  PUBLIC_SITE_TITLE = "Ed Crotty's Professional Portfolio - IT Leader"
  PUBLIC_SITE_DESCRIPTION = "Ed Crotty's Professional Portfolio - IT Leader"

[dev]
command = "npm run dev"
targetPort = 4321
